# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_id', models.IntegerField()),
                ('brand', models.CharField(default='Default Brand', max_length=100)),
                ('name', models.CharField(default='Default Style', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='ShirtColor',
            new_name='StyleColor',
        ),
        migrations.DeleteModel(
            name='Shirt',
        ),
        migrations.RemoveField(
            model_name='stylecolor',
            name='shirt',
        ),
        migrations.AddField(
            model_name='stylecolor',
            name='style',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Style'),
            preserve_default=False,
        ),
    ]
