# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180522_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='id',
        ),
        migrations.AddField(
            model_name='style',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='stylecolor',
            name='slug',
            field=models.SlugField(default='default-color', max_length=40, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='stylecolor',
            unique_together=set([('style', 'color')]),
        ),
    ]
