# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180522_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylecolor',
            name='hex',
            field=models.CharField(default='FFFFFF', max_length=6),
        ),
    ]
