# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stylecolor_hex'),
    ]

    operations = [
        migrations.CreateModel(
            name='InkColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='Default Color', max_length=40)),
                ('hex', models.CharField(default='FFFFFF', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='stylecolor',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
