# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180523_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price4', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price5', models.DecimalField(decimal_places=2, max_digits=6)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Style')),
            ],
        ),
        migrations.AddField(
            model_name='stylecolor',
            name='styles',
            field=models.ManyToManyField(to='api.Style'),
        ),
        migrations.AlterUniqueTogether(
            name='stylecolor',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='stylecolor',
            name='style',
        ),
    ]
