# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180523_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylecolor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stylecolor',
            name='slug',
        ),
    ]
