# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180525_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.URLField(blank=True)),
                ('back', models.URLField(blank=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StyleColor')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Style')),
            ],
        ),
    ]
