# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_styleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylecolor',
            name='slug',
            field=models.SlugField(default='default-color', editable=False, max_length=40),
        ),
    ]
