# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_stylecolor_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Addon', max_length=40)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='stylecolor',
            name='styles',
        ),
        migrations.AddField(
            model_name='style',
            name='colors',
            field=models.ManyToManyField(to='api.StyleColor'),
        ),
        migrations.AlterField(
            model_name='styleimage',
            name='back',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='styleimage',
            name='front',
            field=models.URLField(blank=True, null=True),
        ),
    ]
